Models/GLM/ViewModels/ExcelReportsViewModel.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Linq;
using System.Threading.Tasks;

namespace DataSystem.Models.GLM.ViewModels
{
    public class ExcelReportsViewModel
    {
        [Required]
        public string ReportId { get; set; }

        [Required]
        [Display(Name = "Section")]
        public List<long> SectionIds { get; set; }

        public List<Section> Sections { get; set; }
    }
}

Controllers/GLM/ExcelReportsController.cs
using DataSystem.Models;
using DataSystem.Models.GLM;
using DataSystem.Models.GLM.Dtos;
using DataSystem.Models.GLM.ViewModels;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;
using Syncfusion.XlsIO;
using System;
using System.Collections.Generic;
using System.Data;
using System.IO;
using System.Linq;

namespace DataSystem.Controllers.GLM
{
    [Authorize(Roles = "administrator,unicef,pnd,dataentry,guest")]
    public class ExcelReportsController : BaseController
    {
        protected readonly WebNutContext _context;
        private readonly UserManager<ApplicationUser> _userManager;
        public ExcelReportsController(WebNutContext context, UserManager<ApplicationUser> userManager)
        {
            _context = context;
            _userManager = userManager;
        }

        public IActionResult KeyFindings()
        {
            var Years = new List<int?>();
            var yearList = _context.ReportsView.Select(m => new { m.Year }).Distinct().Where(m => m.Year != null).ToList();

            foreach (var yl in yearList)
            {
                Years.Add(yl.Year);
            }

            var provinces = _context.Provinces.Select(m => new ProvinceDropdownDto { Id = m.ProvCode, Name = m.ProvName })
                .OrderBy(m => m.Name)
                .ToList();

            var vm = new ReportDownloadViewModel()
            {
                Provinces = provinces,
                Years = Years
            };

            return View(vm);
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public IActionResult KeyFindings(ReportDownloadViewModel vm)
        {
            if (!ModelState.IsValid)
            {
                var Years = new List<int?>();
                var yearList = _context.ReportsView.Select(m => new { m.Year }).Distinct().Where(m => m.Year != null).ToList();

                foreach (var yl in yearList)
                {
                    Years.Add(yl.Year);
                }

                var provinces = _context.Provinces.Select(m => new ProvinceDropdownDto { Id = m.ProvCode, Name = m.ProvName })
                    .OrderBy(m => m.Name)
                    .ToList();

                vm.Provinces = provinces;
                vm.Years = Years;

                return View(vm);
            }

            // get reports
            var reports = _context.ReportsView
                .Where(m => m.ProvinceId == vm.ProvinceId && m.Year == vm.Year)
                .OrderBy(m => m.Id)
                .OrderBy(m => m.ReportReceivedDate)
                .ToList();


            if (reports.Count > 0)
            {
                var sections = _context.Sections
                    .Where(m => m.Id == 21)
                    .OrderBy(m => m.SortOrder)
                    .ToList();

                var scqfs = _context.SectionColQuestionFields
                    .Where(m => m.SectionId == 21)
                    .ToList();

                var fieldOptionsAll = _context.FieldOptions.ToList();
                var fieldOptions = new List<FieldOption>();

                var tables = new List<DataTable>();

                if (scqfs.Count > 0)
                {
                    foreach (var section in sections)
                    {
                        var columns = scqfs
                            .Select(m => new {
                                Id = m.ColumnId,
                                SectionId = m.SectionId,
                                Title = m.ColumnTitle,
                                SortOrder = m.CSortOrder,
                                Type = m.ColumnType
                            })
                            .Distinct()
                            .Where(m => m.SectionId == section.Id)
                            .ToList();

                        var questions = scqfs
                            .Select(m => new {
                                Id = m.QuestionId,
                                SectionId = m.SectionId,
                                Title = m.QuestionTitle,
                                SortOrder = m.QSortOrder
                            })
                            .Distinct()
                            .Where(m => m.SectionId == section.Id)
                            .ToList();

                        // create data tabel
                        var sectionTable = new DataTable(section.Title);
                        sectionTable.TableName = section.Title;

                        // add the main columns
                        //sectionTable.Columns.Add("?");
                        sectionTable.Columns.Add("Province");
                        sectionTable.Columns.Add("District");
                        sectionTable.Columns.Add("Facility");
                        sectionTable.Columns.Add("Year");
                        sectionTable.Columns.Add("Month");
                        sectionTable.Columns.Add("Date");

                        if (columns.Count > 0 && questions.Count > 0)
                        {
                            // add columns to the table
                            foreach (var c in columns)
                            {
                                if (c.Type == "standard")
                                {
                                    sectionTable.Columns.Add(c.Title);
                                }
                            }

                            // add report rows to the table
                            foreach (var report in reports)
                            {
                                // add question rows to the table
                                foreach (var q in questions)
                                {
                                    DataRow tableRow = sectionTable.NewRow();

                                    // add question title
                                    //tableRow["?"] = q.Title;

                                    // add report column titles
                                    tableRow["Province"] = report.Province;
                                    tableRow["District"] = report.District;
                                    tableRow["Facility"] = report.Facility + " / " + report.FacilityID;
                                    tableRow["Year"] = report.Year;
                                    tableRow["Month"] = report.Month;
                                    tableRow["Date"] = String.Format("{0:MM/dd/yyyy}", report.ReportReceivedDate);

                                    // add fields data to the row
                                    foreach (var c in columns)
                                    {
                                        //var field = _context.Fields
                                        //    .Include(m => m.FieldOptions)
                                        //    .Where(m => m.QuestionId == q.Id && m.ColumnId == c.Id)
                                        //    .SingleOrDefault();

                                        var field = scqfs
                                            .Select(m => new
                                            {
                                                Id = m.FieldId,
                                                DataType = m.DataType,
                                                InputType = m.InputType,
                                                ColumnId = m.ColumnId,
                                                QuestionId = m.QuestionId,
                                            })
                                            .Where(m => m.QuestionId == q.Id && m.ColumnId == c.Id)
                                            .SingleOrDefault();

                                        if (field != null)
                                        {
                                            // get field options for the dropdown types
                                            if (field.InputType == "dropdown" && field.InputType != "yesno")
                                            {
                                                fieldOptions = fieldOptionsAll
                                                    .Select(m => new FieldOption
                                                    {
                                                        Value = m.Value,
                                                        Caption = m.Caption,
                                                        FieldId = m.FieldId
                                                    })
                                                    .Where(m => m.FieldId == field.Id)
                                                    .ToList();
                                            }

                                            // add text field value
                                            if (field.DataType == "text")
                                            {
                                                if (_context.TextValues.Any(m => m.FieldId == field.Id && m.ReportId == report.Id))
                                                {
                                                    var textValue = _context.TextValues
                                                    .Where(m => m.ReportId == report.Id && m.FieldId == field.Id)
                                                    .SingleOrDefault();

                                                    if (field.InputType == "dropdown" && field.DataType != "yesno")
                                                    {
                                                        

                                                        foreach (var fo in fieldOptions)
                                                        {
                                                            if (fo.Value == textValue.Data)

Views/ExcelReports/DownloadSections.cshtml
@model  DataSystem.Models.GLM.ViewModels.ExcelReportsViewModel
@{
    ViewData["Title"] = "Excel Report";
}
<div class="card">
    <div class="card-header">
        <h2>@ViewData["Title"]</h2>
    </div>

    <div class="card-body">
        @using (Html.BeginForm("DownloadSections", "ExcelReports"))
        {
            @Html.HiddenFor(m => m.ReportId)

            <div class="row">
                <div class="col-md-6">
                    <div class="form-group">
                        @Html.LabelFor(m => m.SectionIds, new { @class = "control-label" })
                        @Html.DropDownListFor(m => m.SectionIds, new MultiSelectList(Model.Sections, "Id", "Title"), "", new { @class = "form-control", multiple = "multiple", size="14" })
                        @Html.ValidationMessageFor(m => m.SectionIds)
                    </div>

                    <div class="form-group">
                        <button type="submit" class="btn btn-primary">
                            <span class="glyphicon glyphicon-download"></span> Download
                        </button>
                    </div>
                </div>
            </div>
        }
    </div>
</div>

Views/ExcelReports/KeyFindings.cshtml
@model DataSystem.Models.GLM.ViewModels.ReportDownloadViewModel
@{
    ViewData["Title"] = "Key Findings Report To Excel";
}
<div class="card">
    <div class="card-header">
        <h2>@ViewData["Title"]</h2>
    </div>

    <div class="card-body">
        @using (Html.BeginForm("KeyFindings", "ExcelReports"))
        {
            <div class="row">
                <div class="col-md-6">
                    <div class="form-group">
                        @Html.LabelFor(m => m.ProvinceId, new { @class = "control-label" })
                        @Html.DropDownListFor(m => m.ProvinceId, new MultiSelectList(Model.Provinces, "Id", "Name"), "Select Province", new { @class = "form-control" })
                        @Html.ValidationMessageFor(m => m.ProvinceId)
                    </div>

                    <div class="form-group">
                        @Html.LabelFor(m => m.Year, new { @class = "control-label" })
                        @Html.DropDownListFor(m => m.Year, new MultiSelectList(Model.Years), "Select Year", new { @class = "form-control" })
                        @Html.ValidationMessageFor(m => m.Year)
                    </div>

                    <div class="form-group">
                        <button type="submit" class="btn btn-primary">
                            <span class="glyphicon glyphicon-download"></span> Download Report
                        </button>
                    </div>
                </div>
            </div>
        }
    </div>
</div>